### ISSUE TITLE
Javascript String.prototype.replace() only replaces the first instance of hyphen

### ISSUE THREAD

**Issue by wtang-8** [slawlor/safeguid#4]
If the guid is:
a0f203c6-9037-4103-9ae9-b65522d04730

it will become:
a0f203c69037-4103-9ae9-b65522d04730 

instead of:

a0f203c6903741039ae9b65522d04730

https://github.com/slawlor/safeguid/blob/ce497b74af55954686e264d847aff771bc6540d9/lib/guid-sets.ts#L7

**Comment by slawlor** [comment]
Yes it should be 

```javascript
(' ' + value).slice(1).replaceAll('-', '').toLowerCase()
```
