### ISSUE TITLE
Modify createMap method return type

### ISSUE THREAD

**Issue by wtang-8** [slawlor/safeguid#5]
https://github.com/slawlor/safeguid/blob/ce497b74af55954686e264d847aff771bc6540d9/lib/safeguid.ts#L100

I think the return type should be `GuidMap<T>`, so that we can call `GuidMap<T>.get( Guid | string )`. 
In fact, `Map<IGuid,T>.get` method signature only accepts a `string` as parameter.
Otherwise, we need to manually cast the returned object to `GuidMap<T>` in order to be able to pass a string to the `get` method.

**Comment by slawlor** [comment]
Since ```IGuid``` extends ```String``` you should be fine passing the ```IGuid``` instance to the map in the ```.get()``` call.
